{{- if .Values.tensorboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 6006
    targetPort: 6006
    protocol: TCP
    name: tensorboard
  selector:
    release: {{ .Release.Name }}
    role: tensorboard
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tensorboard.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        role: tensorboard
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: tensorboard
          image: registry.harbor:5000/sky-firmament/tensorflow:{{ .Values.version.variables.version.value }}
          command: ["tensorboard"]
          args:
          - --logdir={{ .Values.persistence.variables.logDir.value }}
          - --port=6006
          ports:
          - containerPort: 6006
          resources:
            requests:
              cpu: {{ .Values.tensorboard.variables.cpuRequest.value }}m
              memory: {{ .Values.tensorboard.variables.memoryRequest.value }}Mi
          volumeMounts: 
          - name: data
            mountPath: {{ .Values.persistence.variables.mountPath.value }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.variables.pvc.value }}
{{- end -}}
